services:
  web:  # Our Flask website application
    build:  # Build image from Dockerfile in ./web directory
      context: ./web
    hostname: web
    container_name: web
    ports: # Map host port 3500 to container port 3500
      - "3500:3500"
    volumes: # Mount code into container for live updates
      - ./web:/app
    networks: # Join a shared network so services can communicate
      - my-network
    depends_on:  # Ensure web starts after database and admin UI
      - db
      - mongo-express

  db:  # MongoDB database service
    image: mongo:latest
    hostname: db
    container_name: db
    restart: unless-stopped
    command: [ "--bind_ip_all" ] # Allow connections from any IP
    # expose: # Expose default Mongo port
    #   - "27017:27018"
    volumes: # Persist database files on the host
      - ./data/db:/data/db
    networks:
      - my-network
    environment:
      - MONGO_URI=mongodb://db:27017/db
    ports:
      - "27018:27017"
    

  mongo-express: # Mongo Express admin UI
    image: mongo-express:latest
    hostname: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:  # Map host port 8083 to the admin UI port
      - "8083:8081"
    environment: # Tell mongo-express where to find the database
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_URL=mongodb://db
    networks:
      - my-network

networks: # Define a custom network for service communication
  my-network:
